# Generated by Django 4.0.1 on 2022-02-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
                ('budget_description', models.CharField(max_length=200)),
                ('budget_type', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='daily', max_length=15)),
                ('currency', models.CharField(choices=[('dollar', 'dollar'), ('yuan', 'yuan'), ('naira', 'naira'), ('euro', 'euro')], default='naira', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=15)),
                ('item_amount', models.IntegerField()),
                ('budget', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.client')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.client'),
        ),
    ]
